version: '3'
services:
  database:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: cases123
      MYSQL_DATABASE: case_studies
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  webapp:
    build: ./webapp
    restart: always
    ports:
      - "80:80"
    depends_on:
      - database

